@startuml : diagramm
left to right direction
(0)-->(включить)
(включить)-->(выключить) : выключение робота
(включить)-->(команда) : получение команды
(начать движение)-->(стоп) : остановка
(команда)-->(выключить пулевиризатор) : закончить закраску
(команда)-->(включить пулевиризатор) : закраска графити
(стоп)-->(начать движение) : начать движение
(выключить)-->(включить) : включение робота
(стоп)-->(выключить) : выключение робота
(выключить пулевиризатор)-->(стоп) : закраска окончена
(команда)-->(начать движение) : робот начал движение 
(стоп)-->(команда) : получение команды
(включить пулевиризатор)-->(команда) : получение команды
@enduml